name: Deploy Simple Java App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Java
        run: |
          mkdir -p target
          javac -d target src/main/java/org/example/Main.java
          # Создаём JAR
          cd target
          jar cfe app.jar org.example.Main org/example/Main.class

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/java-app
            # Установка Java (версия по умолчанию)
            sudo apt update
            sudo apt install -y default-jdk
            
            # Запуск приложения
            java -jar app.jar &
            echo "Application started!"